### ISSUE TITLE
IColoredCoin.Amount comingles non-BTC with BTC quantities

### ISSUE THREAD

**Issue by dthorpe** [NicolasDorier/NBitcoin#18]
IColoredCoin inherits Amount property from ICoin.  In the general case, using an ICoin variable, ICoin.Amount maps to the BTC quantity in a transaction output. However, if you assign a colored coin implementation to that ICoin variable, ICoin.Amount then returns the quantity of the asset (books or ships or shares of stock), which is not BTC.

Case in point: TransactionBuilder.Verify contains this line:
```c#
spent += coin is IColoredCoin ? ((IColoredCoin)coin).Bearer.Amount : coin.Amount;
```

This test will have to be repeated in every situation where code wants to tally the BTC in a transaction, and only the BTC. This is code maintenance land mine.

I suggest inverting the IColoredCoin.Bearer relationship such that IColoredCoin.Amount is always the BTC value and some new property (AssetQuantity?) indicates the quantity of the colored asset.  Something like this:

```C#
interface IColoredCoin: ICoin
{
    long AssetQuantity { get;}
}
```

**Comment by andre-amorim** [comment]
I think we going to side-chain debate. My interest is on ring-signature schema, reason based on acronym CIA, standing for confidentiality, integrity and accessibility.
Steps;
1 - Convert original code (http://en.wikipedia.org/wiki/Ring_signature) in python into c#
2 - ...still working
3 -  ........

**Comment by NicolasDorier** [comment]
open a new issue for that, you are out of the topic. I don't see what is the relation between bitcoin and ring sig.

**Comment by andre-amorim** [comment]
Ok Nicolas as "Redmondians" researchers says, we don't want to cause "data-quake". Case Dismissed.
PS-. Nicolas you should read letters exchange between Satoshi and Hal Finney, don't let then make up your mind.

**Comment by NicolasDorier** [comment]
where do they talk about it

**Comment by andre-amorim** [comment]
Well we need to dive into Microsoft PKI modules.. it's long history and
probably we going to end up into a infinity loop ...

---------- Forwarded message ----------

From: Satoshi Nakamoto <satoshi@vistomail.com>

Date: Sat, Jan 10, 2009 at 11:52 AM

Subject: RE:Crash in bitcoin 0.1.0

To: hal.finney@gmail.com

Normally I would keep the symbols in, but they increased the size of the
EXE from 6.5MB to 50MB so I

just couldn't justify not stripping them. I guess I made the wrong
decision, at least for this early

version. I'm kind of surprised there was a crash, I've tested heavily and
haven't had an outright

exception for a while. Come to think of it, there isn't even an exception
print at the end of

debug.log. I've been testing on XP SP2, maybe SP3 is something.

I've attached bitcoin.exe with symbols. (gcc symbols for gdb, if you're
using MSVC I can send you an

MSVC build with symbols)

Thanks for your help!

>Hi Satoshi - I tried running bitcoin.exe from the 0.1.0 package, and

>it crashed. I am running on an up to date version of XP, SP3. The

>debug.log output is attached. There was also a file db.log but it was

>empty.

>

>The crash allowed me to start up a debugger, but there were no

>symbols. The exception was at address 00930AF7. The displayed call

>stack was 942316 called by 508936.

>

>When I have a chance, I'll try building it, although it looks like it

:.  Andre Amorim      .:

Key-ID:

A70B444E

Fingerprint:

FAAD3B6556A8877B938EAB2FC05E2CB0A70B444E

**Comment by NicolasDorier** [comment]
Man, are you alright ? what you say make no sense, and you just speak in github issues that have no relation with what you want.

**Comment by andre-amorim** [comment]
I'm completed all right, maybe to much coffee I confess... and maybe the
knowledge I care not fit on this discussion, while finishing my essay
Routh-Huwitz theorem on kernel ring 0 based protocol implementation. As I
said I apologise for any inconvenience and going into silence mode... It's
sad when you lost the ability to communicate...

**Comment by NicolasDorier** [comment]
I was thinking about adding an abstract layer dealing with "assets" that could easily be used for handling normal Bitcoin, Open Asset Coins, or any other coins.

By coding colored coins, there is too much place where I use "if(coin is ColoredCoin)", there ought to be a better way of doing it.

An "Asset" would have its own type of "Money" independent from Bitcoin, but also have an "Issuer".
For Bitcoin it would be a singleton representing "The BlockChain". For Open Asset it would be the AssetId.

I am incubating this idea for now, this would fix this issue.

**Comment by NicolasDorier** [comment]
@dthorpe I worked on a big refactoring that did the following stuff : 

* Transformed Asset class in AssetMoney (which support arithmetic operations and check for overflow) (8193beb14b4e022091336be78e86e71343cb3a5b)
* Introduce a IMoney interface used by both, AssetMoney and Money, then use it in place of Money in the transaction builder. (b330d70e461f96bcb4b7c5e1685406f57fcce82d)

Would you have time to review and have anything to add ? it would fix this issue, while protecting against bugs mixing apples and oranges.

**Comment by NicolasDorier** [comment]
I am closing that issue, now Money is not used for asset arithmetic. AssetMoney class was created with a common interface called IMoney.
