### ISSUE TITLE
Support for Mnemonic keys?

### ISSUE THREAD

**Issue by mtbitcoin** [NicolasDorier/NBitcoin#63]
I was looking through but could not find so I might have missed it. But is there support for mnemonic keys like what is done in bitcore.io. You enter 12 words, hex generated and used for the seed? I know there is a seed option for the extKey. But is there built-in support for the mnemonic phrases?

Thanks

**Comment by NicolasDorier** [comment]
> Mnemonic mnemo = new Mnemonic(Wordlist.English, WordCount.Twelve);
string str = mnemo.ToString();
ExtKey extKey = mnemo.DeriveExtKey("password");

Or

> Mnemonic mnemo = new Mnemonic("words....", Wordlist.English);

**Comment by mtbitcoin** [comment]
Thanks. But is it possible to use a custom wordlist ?

**Comment by NicolasDorier** [comment]
yes, just new WordList(words)

**Comment by mtbitcoin** [comment]
How would this look like in an example? Something like this?

string[] tmpArr = Strings.Split("like just love know never want ....", " ");
Mnemonic mnemo = new Mnemonic(new WordList(tmpArr), WordCount.Twelve);
string str = mnemo.ToString();

the new Wordlist has 2 additional paramters "space" and "name". What do these represent?

thank you

**Comment by NicolasDorier** [comment]
The wordlist is the dictionary you are using (english,japanese, spanish chinese), if you want to make your own dictionary you need 2048 words. I don't think this is what you mean.

What you want is that.
> Mnemonic mnemo = new Mnemonic("like just love know never wan", Wordlist.English);
var key = mnemo.DeriveExtKey("password")

**Comment by mtbitcoin** [comment]
actually yes, I would want to make my own dictionary? Is this possible from the library to provide a custom wordlist or does this have be compiled at source?

**Comment by NicolasDorier** [comment]
ah I see, yes it is possible, as I said just do : 

> new Wordlist(string[] dictionary);

Name is not really used so you don't care. And space, use ' '. In some language, space is a different character that ' '. For example, japanese use '　' and not ' ' ;)
