### ISSUE TITLE
Weird target address in transaction

### ISSUE THREAD

**Issue by doosterkamp** [NicolasDorier/NBitcoin#68]
Hi Nicolas ...

First of all: I really really love your work on the NBitcoin library!! (A donation will follow soon ;) )

While processing transactions from the blockchain I stumbled upon somethin weird.

Transaction with id '8ebe1df6ebf008f7ec42ccd022478c9afaec3ca0444322243b745aa2e317c272' has an invalid target addres, when decoded with NBitcoin: '76a9146300bf4c5c2a724c280b893807afb976ec78a92b88ac61' ... 
I validated this first against blockr.io (https://btc.blockr.io/tx/info/db3f14e43fecc80eb3e0827cecce85b3499654694d12272bf91b1b2b8c33b5cb), where this address was defined as 'NONSTANDARD', so at first I thought these btc simply were destroyed.

But ...

On a later transaction with id 'db3f14e43fecc80eb3e0827cecce85b3499654694d12272bf91b1b2b8c33b5cb' this output was referenced as a (valid!) input for a transaction. Again I looked it up in blockr.io (https://btc.blockr.io/tx/info/8ebe1df6ebf008f7ec42ccd022478c9afaec3ca0444322243b745aa2e317c272) and again it showed up as 'NONSTANDARD'

The weird this is that I decided to also validate this against an other blockchain explorer and there it was mentioned correctly (address: 1A2UnusrwYr7DbiFbFesRKrbQMiYkj6E84):
http://blockexplorer.com/tx/db3f14e43fecc80eb3e0827cecce85b3499654694d12272bf91b1b2b8c33b5cb
http://blockexplorer.com/tx/8ebe1df6ebf008f7ec42ccd022478c9afaec3ca0444322243b745aa2e317c272

I'm confused now. What's going on here?

**Comment by NicolasDorier** [comment]
Thanks for your support ;)

The NONSTANDARD address has this scriptPubKey.

```
OP_DUP OP_HASH160 6300bf4c5c2a724c280b893807afb976ec78a92b OP_EQUALVERIFY OP_CHECKSIG OP_NOP
```
You can notice that a OP_NOP, was inserted in the scriptPubKey, making it non standard. However OP_NOP is an operation without effect.
It means that the scriptSig of the transaction spending this output is similar to a standard P2PKH payment :

```
<sig> <pubKey>
```

Now bitcoin services might behaves differently one another. Most of them, to know from where the coins came from, just fetch the previous scriptPubKey from the previous transaction.
This is what is doing blockr, so blockr, rightfully so, tells you that the spent coin come from a non standard scriptPubKey.

Other services, like blockexplorer, for performance reasons, try to infer the scriptPubKey from the scriptSig. And where it sees

```
<sig> <pubKey>
```

He thinks, wrongly, that the scriptPubKey is a standard P2PKH.

By the way, I implemented a web service that is integrated to NBitcoin called (for now, but will soon rename and fork the project, RapidBase)
You can install it with nuget : Install-Packeg RapidBase.Client

```
RapidBaseClient client = new RapidBaseClient(new Uri("http://rapidbase-test.azurewebsites.net/"));
var response = client.GetTransaction(new uint256("8ebe1df6ebf008f7ec42ccd022478c9afaec3ca0444322243b745aa2e317c272")).Result;
```

The client API is nicely integrated with NBitcoin API. (you can get balances and all kind of stuff)

**Comment by doosterkamp** [comment]
Hi Nicolas ...

Thanks for the quick response!
Is this something that will be fixed in NBitcoin or should I filter on this in my code myself?

>> By the way, I implemented a web service that is integrated to NBitcoin called RapidBase

Sounds interresting, I will check this out on a later time definitifly.
But .. personally I think that one of the strengths of the NBitcoin library, is that it can operate within the bitcoin network, without depending on 3rd party databases or access...
The only comment I can think of is the lack of (internal) documentation... ;P

**Comment by NicolasDorier** [comment]
> Is this something that will be fixed in NBitcoin or should I filter on this in my code myself?

This is not a bug.

```
OP_DUP OP_HASH160 6300bf4c5c2a724c280b893807afb976ec78a92b OP_EQUALVERIFY OP_CHECKSIG OP_NOP
```
Should not be mistaken for a standard P2PKH payment, and your interface should show that funds come from a non standard scriptPubKey. You should NOT show the expected address.

> The only comment I can think of is the lack of (internal) documentation

Have you seen my [book](http://blockchainprogramming.azurewebsites.net/) ? 

I agree that comments for methods would be great though. (Don't hesitate to pull request if you add some)

**Comment by NicolasDorier** [comment]
@doosterkamp , I thought a little bit about why such OP_NOP could be inserted. it can be used for making arbitrary clients crash. I will detail the explanation on the bitcoin dev forum, because even blockchain info is weak to that. 

Please, DO NOT consider such wierd scriptPubkey as belonging to 1A2UnusrwYr7DbiFbFesRKrbQMiYkj6E84 or you will get crashes with most signers. I will detail that more deeply on the forum tomorrow.

**Comment by NicolasDorier** [comment]
@doosterkamp  I close that if it respond to your question.

By the way, I forked the project RapidBase. I doubt other maintainers will continue to develop it.
I forked and rename [QBitNinja](https://github.com/QBitNinja/QBitNinja)

Mainnet server : http://api.qbit.ninja/
Testnet : http://tapi.qbit.ninja/
Documentation: http://docs.qbitninja.apiary.io/
Nuget Package : QBitNinja.Client
