### ISSUE TITLE
P2SH CheckScriptSig succeeds for P2PKH

### ISSUE THREAD

**Issue by dthorpe** [NicolasDorier/NBitcoin#74]
PayToScriptHashTemplate.Instance.CheckScriptSig returns TRUE when given a public key hash scriptsig.

Similarly, PayToScriptHashTemplate.Instance.ExtractScriptSigParameters() returns a non-null sigparams result which has garbage data (nonsense RedeemScript)

This doesn't create a problem within NBitcoin  because just about everywhere inside NBitcoin that operates on scriptsigs consistently tests for P2PKH before P2SH. 

But if a (naively written) app just wants to do a "quick" test of whether a script is a P2SH scriptsig, the P2SH template functions don't work - that is, the P2SH functions don't fail or reject P2PKH scripts.

I can't be sure, but this feels like a change in behavior from builds of NBitcoin several months ago. I recently updated to the latest NBitcoin build after several months on a static branch, and now suddenly my P2SH checks are running amok. 

I can work around this issue by testing for P2PKH before testing for P2SH, but this feels like a kludge. Can't the PayToScriptHashTemplate.Instance.CheckScriptSig and related functions be more authoritative about whether a script is / appears to be a well-formed script hash script?

**Comment by NicolasDorier** [comment]
fixed in the last package. I'm checking if there is any invalid OP in the script.
