### ISSUE TITLE
Questions about tests

### ISSUE THREAD

**Issue by lontivero** [NicolasDorier/NBitcoin#75]
Hi @NicolasDorier 

Unit tests run and pass perfectly well. However I found some friction in a very few. I would like to know if some of these suggestions make sense for you.

* **NBitcoin.Tests.Benchmark.BlockDownloadFromNetwork**
````using(var node = Node.Connect(Network.Main, "192.168.0.7", new NodeConnectionParameters())````
You are running a bitcoin node in 192.168.0.7 but I think most devs don't. 
Could that be replace by?:
````var node_ip = Environment.ExpandEnvironmentVariables("bitcoin_node_ip");
node_ip = string.IsNullOrEmpty(node_id) ? "127.0.0.1" : node_ip;````
  
I assume someone who download the NBitcoin source code could be running a node in 127.0.0.1. And even when that could be not true, it is more probable to have a node in localhost than in 192.168.0.7.
So, You could define the "bitcoin_node_ip" with 192.168.0.7 to reduce just a bit the friction for new devs.  

* **NBitcoin.Tests.Benchmark.BlockDirectoryScanSpeed
NBitcoin.Tests.Benchmark.BenchmarkBlockIndexing
NBitcoin.Tests.Benchmark.BenchmarkCreateChainFromBlocks
NBitcoin.Tests.Benchmark.BenchmarkTemplate**
```BlockStore store = new BlockStore(@"**(Z|E)**:\Bitcoin\blocks", Network.Main);```
Could that be replaced by?:
```var blocksFolder = Environment.ExpandEnvironmentVariables("%appdata%\\Bitcoin\\blocks\\");```

* **NBitcoin.Tests.MnemonicReference_tests.CanCreateBrainAddressFromNetwork**
Needs a node running in the default porr 8333. Other tests fail with:
```throw new InvalidOperationException("No bitcoin-qt or bitcoinq process running with rpc server on test net (\"bitcoin-qt.exe\" -testnet -server -rpcuser=NBitcoin -rpcpassword=NBitcoinPassword )");```
I think it was a good idea and this test could fail with the same kind message.

* **NBitcoin.Tests.MnemonicReference_tests.CanCreateBrainAddress**
Result Message:	NBitcoin.InvalidBrainAddressException : This block does not exists
(I didn't check why, yet)

**Comment by NicolasDorier** [comment]
So for the tests, I advise you to group them by Trait.

The "Benchmark" are not meant to be runned daily, I mostly use them for playing with performance improvement.

Same things with those without Trait, they are in a "testing the test" phase. Or in other words, some stuff that are not yet really stable that I will improve later.

The rest of the tests should run fine if you have a local bitcoind with RPC enabled.

**Comment by lontivero** [comment]
What you say is clear, but you didn't answered my questions. Don't you think that would be better to use *%appdata%\Bitcoin\blocks\* instead of *Z:\Bitcoin\blocks*? Because others are forced to create a map just because it's more comfortable for you (maybe it could be easier for others if some tests don't fail in theirs env. )

**Comment by NicolasDorier** [comment]
I understand, but it would prevent me to run it (I have SSD, not enough space for blockchain)

Since these tests are meant to be runned manually in debug mode, I expect people to just change the path when they need to run it. (If someone commit with their own folder, I don't really care, I will just change it manually when I need to measure some stuff)

I think I will change the traits of these test to something like "DontRunAutomatically" or "PlaygroundCode".

**Comment by lontivero** [comment]
Ok, thank you Nicolas.
