### ISSUE TITLE
RNGCryptoServiceProvider Dispose

### ISSUE THREAD

**Issue by lontivero** [NicolasDorier/NBitcoin#76]
Hi @NicolasDorier 

Reading the RNGCryptoServiceProvider documentation on MSDN, it says:

>>This type implements the IDisposable interface. When you have finished using the type, you should dispose of it either directly or indirectly.

It is a common suggestion to use the Dispose() method to free memory with sensitive information immediately.

NBitcoin keeps only one long-life RNGCryptoServiceProvider instance. Do you think it worth changing that?

As a side question, can I add you to skype? I would like to have a less bureaucratic mean for this kind of questions/suggestions.

**Comment by lontivero** [comment]
Well, after some research I found this: http://stackoverflow.com/questions/26371951/should-i-cache-rngcryptoserviceprovider-randomnumbergenerator-instances

The problem is that I am not sure if Mono implements this in exactly the same way.

**Comment by NicolasDorier** [comment]
yes "nicolas.dorier" is my skype.

For Mono, it does not. This is why I permit to submit your own "IRandom" implementation. In fact most of methods in NBitcoin will crash until you implement your own IRandom.

For the Android specific version, I use the SecureRandom class by default so it works right out of the box, but not the portable ones.

I don't think it is worth changing it, I'm not sure about the performance impact, nor security impact.

**Comment by lontivero** [comment]
Sure, the IRandom interface is about that. 

But just imagine this scenario:
Someone is using the *RNGCryptoServiceProvider* as his RNG provider. This person is not creating *RNGCryptoServiceProvider* instances in an explicit way but using the factory method instead. In code:

```var _prng = new RNGCryptoServiceProvider(); // he doesn't do this!```
but
```var _prng =  RandomNumberGenerator.Create(); // he is doing it in this way```

**Note:** by default RandomNumberGenerator.Create() creates an RNGCryptoServiceProvider instance so, both lines above are equivalent.
  
One day, this person wants to use his own RNG for all his applications (probably for performance, security or stupidity) and for that reason he decide to update his machine.config as follow:

```
<mscorlib>
		<cryptographySettings>
			<cryptoNameMapping>
				<cryptoClasses>
					<cryptoClass MySuperFastAndSecureRNG="MyCompany.Security.AwesomeRNGServiceProvider, MyCompany.Security, Version=19.0.0.0, Culture=neutral, PublicKeyToken=........."/>
				</cryptoClasses>
				<nameEntry name="System.Security.Cryptography.RandomNumberGenerator" class="MySuperFastAndSecureRNG" />
				<nameEntry name="RandomNumberGenerator" class="MySuperFastAndSecureRNG" />
```

Now, all his .NET applications will be using his own *MyCompany.Security.AwesomeRNGServiceProvider* class. But what if he wants to use this RNG with NBitcoin? Well, he will need to submit his alghoritm to you (probably he doesn't want to share it or it could be a propietary RNG, who knows).

I think that given .NET and Mono provide an standard mechanism for changing the RNG provider, it would be wise to use it. I have nothing against IRandom interface, it is okay. What I suggest is using the abstraction RandomNumberGenerator.Create() instead of the concrete implementation.

**Comment by NicolasDorier** [comment]
oh sorry, I had not understood what you meant. I did not know about RandomNumberGenerator class, I thought you wanted I use a factory pattern instead of IRandom.
It works with Mono are you sure ?

I'm a bit worried about a malware changing the machine.config though.

**Comment by lontivero** [comment]
Yes, I am sure. Take a look at this README file: https://github.com/mono/mono/blob/master/mcs/class/Mono.Security.Win32/README

Malware can do whatever they want to do. They could modify/inject the CLR if are designed to do that.

**Comment by NicolasDorier** [comment]
interesting, sadly does not exist in portable library. :( 

I am mixed about using this one over the current RNGCrypto by default. The point of using RNGCrypto explicitely by default is that a malware can't just modify machine.config for changing the prng. What do you think ?

I may just provide an implementation, but not use it by default ?

**Comment by lontivero** [comment]
Servers with malware are seriouly compromised. Who knows what a malware can do. It can expose a remote shell, modify whatever it was designed to modify, replace dlls, inject itself in other processes, wipe processes memory, export wallets, install certificates.... who knows. 

I watched a BlackHat Conf video where the hacker demostrated how to modify the .NET framework (nothing too funcy)  What I mean is that a virus could modify the IRandom.GetBytes in a way it returns predictable values. 

It's okay to worry about these kind of things because we are dealing with bitcoins (money) but I think there is nothing to do when your server is running malware. You cannot develop a malware-proof/resistant software.

Anyway, I think this requires further discussions and probably other opinions. In fact, if you use RandomNumberGenerator.Create, you will be allowing custom RNGs and that means you should invoke the RNG Dispose method (because you don't know its implementation details). 

On the other hand, what if microsoft changes (in a future) the default RNG returned by RandomNumberGenerator.Create? It could be a good thing if it is for security reasons. It could be bad if performance is not good.

Can we let this thread open?

**Comment by NicolasDorier** [comment]
yes let's let it open. What I fear is that it is simpler to just modify one line in machine.config than subverting the CLR. It is the point that I fear most.

**Comment by lontivero** [comment]
If you fear about modification in machine.config, you shouldn't use things like this one:

```
using(var sha = System.Security.Cryptography.SHA256.Create())
```

Because this factory method creates a SHA256 instance that can be changed in the machine.config.
Remember that SHA256 is an abstract class, what means it was designed to be used as a base class for other/custom SHA256 implementations.

Here is the factory method. 
 
```  
public new static SHA256 Create(string hashName)
{
	return (SHA256)CryptoConfig.CreateFromName(hashName);
}
```

Please, take Reflector or ILSpy and see it by yourself. Go deeper and deeper and you will understand what I talk about.

**Comment by NicolasDorier** [comment]
very true, I will fix that. But having a bogus SHA256 is not as dangerous has having a bogus prng.

**Comment by NicolasDorier** [comment]
fixed 9db4a196b0b2051b95318bb4bb4d4ab4fd18038b (wrong issue number though :D)

**Comment by NicolasDorier** [comment]
do I close that ? Implementers of IRandom are responsible to Dispose their own internal generator. We don't need to dispo RNGCryptoServiceProvider though.
If one is using the factory method (`RandomGenerator.Create`), then he should dispose it. But we are not.

**Comment by lontivero** [comment]
I close it.
