### ISSUE TITLE
Convert ENCRYPTED_SECRET_KEY_NO_EC to ENCRYPTED_SECRET_KEY_EC?

### ISSUE THREAD

**Issue by YellowGreenBlue** [NicolasDorier/NBitcoin#79]
Hello,

I'm trying to get some old keys stored as ENCRYPTED_SECRET_KEY_NO_EC converted to ENCRYPTED_SECRET_KEY_EC. I have the passphases, private keys, etc. Just not sure if this is 1) possible, and 2) the code required to do it.

Thanks

**Comment by NicolasDorier** [comment]
No, it is not possible. NO_EC is not an "old version" of EC, they have different purposes. (See [here](https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki#Encryption_when_EC_multiply_flag_is_not_used))

NO_EC is used to turn any unencrypted Key into an encrypted one.
EC is done so you can delegate encrypted key generation to an untrusted third party. (through a `BitcoinPassphraseCode`)

If you are using NBitcoin, you can use the static method `BitcoinEncryptedSecret.Create(string wif)` to parse them, whatever their derived type is.

Take a look in [my book](https://blockchainprogramming.azurewebsites.net/), I explain how both of them works.

**Comment by YellowGreenBlue** [comment]
Thanks for the nice and clear answer! While I don't need the benefits of EC, it seems that there's no disadvantages to it, right? I might as well leave the EC keys as EC, and leave the NO_EC keys as NO_EC, if I understand correctly.

**Comment by NicolasDorier** [comment]
This is right, there is no reason to convert one into the other. Only if you generate a new key, you have the choice about which type to use. 

But since wallets should support both, there is no preferences to have.
If you decide to use EC, then take a look at my book, you need to use the `BitcoinPassphraseCode` class.

**Comment by YellowGreenBlue** [comment]
Thanks for the quick response! Keep up the great work!
