### ISSUE TITLE
Not buildable

### ISSUE THREAD

**Issue by bitcoinbrisbane** [NicolasDorier/NBitcoin#96]
A NuGet package is not committed to GitHub.  See pull request #95.  Lets get a build server?

**Comment by NicolasDorier** [comment]
I have internally a build server. Which is why I am surprised. I'm trying to pin down why my build server run fine.

**Comment by NicolasDorier** [comment]
Let's continue talking about that directly on the PR.

**Comment by bitcoinbrisbane** [comment]
Might be on the disk of the build server? I found a free online build server that seems alright too. I'll send over the details for you to have a look.

Sent from my iPhone

On 21 Jun 2015, at 7:03 am, Nicolas Dorier <notifications@github.com<mailto:notifications@github.com>> wrote:


I have internally a build server. Which is why I am surprised. I'm trying to pin down why my build server run fine.

-

**Comment by NicolasDorier** [comment]
continue to talk on the PR #95 I'm seeing that the PR is changing the packages.config by adding a xunit visualstudio package... but as you can see on master, it already exists.
